name: Build Debian Package

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-slim
    strategy:
      matrix:
        arch: [armhf, arm64, amd64, i386]

    steps:
      - uses: actions/checkout@v4

      - name: Install Libs
        run: sudo apt-get update && sudo apt-get install -y build-essential dpkg-dev

      - name: Set up Environment
        run: |
          echo "ARCH=${{ matrix.arch }}" > .env
          echo "VERSION=${{vars.MAJOR}}.${{vars.MINOR}}.${{vars.PATCH}}" >> .env

      - name: Build Debian Package
        run: |
          make 
          make deb

      - name: Upload Debian Package
        uses: actions/upload-artifact@v6
        with:
           name: hello-world-${{ matrix.arch }}.deb
           path: "*.deb"
  release:
    runs-on: ubuntu-slim
    needs: build
    permissions:
      actions: write
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{vars.MAJOR}}.${{vars.MINOR}}.${{vars.PATCH}}
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Increment BUILD_NUMBER repo variable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          VAR_NAME: BUILD_NUMBER
        run: |
          set -e

          # Get current value
          CURRENT=$(curl -s \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$OWNER/$REPO/actions/variables/$VAR_NAME \
            | jq -r '.value')

          echo "Current $VAR_NAME=$CURRENT"

          # Increment
          NEXT=$((CURRENT + 1))
          echo "Next $VAR_NAME=$NEXT"

          # Update variable
          curl -s -X PATCH \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$OWNER/$REPO/actions/variables/$VAR_NAME \
            -d "{\"value\":\"$NEXT\"}"